### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by cblanken** [cblanken/tato-web-recorder#1]
Getting OOM errors after loading multiple input files without reloading the page.

The SentenceImporter probably needs to trigger some cleanup of existing recordings to conserve space.

Below are some of the errors from the worklet:
```
failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
```

```
Aborted(RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance)
```

```
Uncaught (in promise) RuntimeError: Aborted(RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance). Build with -sASSERTIONS for more info.
    at ve (workletProcessor-_AMzdT6B.js:1:6381)
    at workletProcessor-_AMzdT6B.js:1:7074
```

**Comment by cblanken** [comment]
This should be resolved by commit c8727c4c39b238b070ea85e2524907476981cb85
